# Etapa base: Node.js
FROM node:latest


# Crear directorio de la app
WORKDIR /app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto de Angular
EXPOSE 4200

# Ejecutar Angular escuchando en todas las interfaces
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
