services:
  minio:
    image: minio/minio
    # image: docker.io/bitnami/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: W43z5c1Qqt3Y
      # MINIO_SERVER_URL: http://localhost:9000
      # MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_BUCKET: sistema-archivos-simr
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    command: server /data --console-address ":9001"

volumes:
  minio-data:
  minio-config:
