# Usamos la imagen oficial de Node.js
FROM node:22-alpine

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código fuente
COPY . .

# Copiamos el archivo .env dentro de la imagen
COPY .env .env

# Exponemos el puerto que usa Express (por defecto 3000)
EXPOSE 3000

# Variable de entorno opcional
ENV NODE_ENV=production

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]
