#!/usr/bin/env node

const mongoose = require("mongoose");
const config = require("../config/config");

const connectDB = async () => {
  try {
    console.log("Conectando a MongoDB:", config.db);
    await mongoose.connect(config.db);
    console.log("✅ Conectado a MongoDB");
  } catch (error) {
    console.error("❌ Error conectando a MongoDB:", error);
    process.exit(1);
  }
};

const LUGARES = [
  // ===== PAÍSES Y CAPITALES DEL MUNDO =====
  "Afganistán (Kabul)",
  "Albania (Tirana)",
  "Alemania (Berlín)",
  "Andorra (Andorra la Vieja)",
  "Angola (Luanda)",
  "Antigua y Barbuda (Saint John's)",
  "Arabia Saudita (Riad)",
  "Argelia (Argel)",
  "Argentina (Buenos Aires)",
  "Armenia (Ereván)",
  "Australia (Camberra)",
  "Austria (Viena)",
  "Azerbaiyán (Bakú)",
  "Bahamas (Nasáu)",
  "Bangladés (Daca)",
  "Barbados (Bridgetown)",
  "Baréin (Manama)",
  "Bélgica (Bruselas)",
  "Belice (Belmopán)",
  "Benín (Porto Novo)",
  "Bielorrusia (Minsk)",
  "Birmania/Myanmar (Naypyidaw)",
  "Bolivia (Sucre)",
  "Bosnia y Herzegovina (Sarajevo)",
  "Botsuana (Gaborone)",
  "Brasil (Brasilia)",
  "Brunéi (Bandar Seri Begawan)",
  "Bulgaria (Sofía)",
  "Burkina Faso (Uagadugú)",
  "Burundi (Gitega)",
  "Bután (Timbu)",
  "Cabo Verde (Praia)",
  "Camboya (Nom Pen)",
  "Camerún (Yaundé)",
  "Canadá (Ottawa)",
  "Catar (Doha)",
  "Chad (Yamena)",
  "Chile (Santiago)",
  "China (Pekín)",
  "Chipre (Nicosia)",
  "Ciudad del Vaticano (Ciudad del Vaticano)",
  "Colombia (Bogotá)",
  "Comoras (Moroni)",
  "Corea del Norte (Pionyang)",
  "Corea del Sur (Seúl)",
  "Costa de Marfil (Yamusukro)",
  "Costa Rica (San José)",
  "Croacia (Zagreb)",
  "Cuba (La Habana)",
  "Dinamarca (Copenague)",
  "Dominica (Roseau)",
  "Ecuador (Quito)",
  "Egipto (El Cairo)",
  "El Salvador (San Salvador)",
  "Emiratos Árabes Unidos (Abu Dabi)",
  "Eritrea (Asmara)",
  "Eslovaquia (Bratislava)",
  "Eslovenia (Liubliana)",
  "España (Madrid)",
  "Estados Unidos (Washington D.C.)",
  "Estonia (Tallin)",
  "Etiopía (Adís Abeba)",
  "Filipinas (Manila)",
  "Finlandia (Helsinki)",
  "Fiyi (Suva)",
  "Francia (París)",
  "Gabón (Libreville)",
  "Gambia (Banjul)",
  "Georgia (Tiflis)",
  "Ghana (Acra)",
  "Granada (Saint George's)",
  "Grecia (Atenas)",
  "Guatemala (Ciudad de Guatemala)",
  "Guinea (Conakri)",
  "Guinea Ecuatorial (Malabo)",
  "Guinea-Bisáu (Bisáu)",
  "Guyana (Georgetown)",
  "Haití (Puerto Príncipe)",
  "Honduras (Tegucigalpa)",
  "Hungría (Budapest)",
  "India (Nueva Delhi)",
  "Indonesia (Yakarta)",
  "Irak (Bagdad)",
  "Irán (Teherán)",
  "Irlanda (Dublín)",
  "Islandia (Reikiavik)",
  "Islas Marshall (Majuro)",
  "Islas Salomón (Honiara)",
  "Israel (Jerusalén)",
  "Italia (Roma)",
  "Jamaica (Kingston)",
  "Japón (Tokio)",
  "Jordania (Amán)",
  "Kazajistán (Astaná)",
  "Kenia (Nairobi)",
  "Kirguistán (Biskek)",
  "Kiribati (Tarawa)",
  "Kuwait (Ciudad de Kuwait)",
  "Laos (Vientián)",
  "Lesoto (Maseru)",
  "Letonia (Riga)",
  "Líbano (Beirut)",
  "Liberia (Monrovia)",
  "Libia (Trípoli)",
  "Liechtenstein (Vaduz)",
  "Lituania (Vilna)",
  "Luxemburgo (Luxemburgo)",
  "Madagascar (Antananarivo)",
  "Malasia (Kuala Lumpur)",
  "Malaui (Lilongüe)",
  "Maldivas (Malé)",
  "Malí (Bamako)",
  "Malta (La Valeta)",
  "Marruecos (Rabat)",
  "Mauricio (Port Louis)",
  "Mauritania (Nuakchot)",
  "México (Ciudad de México)",
  "Micronesia (Palikir)",
  "Moldavia (Chisináu)",
  "Mónaco (Mónaco)",
  "Mongolia (Ulán Bator)",
  "Montenegro (Podgorica)",
  "Mozambique (Maputo)",
  "Namibia (Windhoek)",
  "Nauru (Yaren)",
  "Nepal (Katmandú)",
  "Nicaragua (Managua)",
  "Níger (Niamey)",
  "Nigeria (Abuya)",
  "Noruega (Oslo)",
  "Nueva Zelanda (Wellington)",
  "Omán (Mascate)",
  "Países Bajos (Ámsterdam)",
  "Pakistán (Islamabad)",
  "Palaos (Melekeok)",
  "Panamá (Ciudad de Panamá)",
  "Papúa Nueva Guinea (Puerto Moresby)",
  "Paraguay (Asunción)",
  "Perú (Lima)",
  "Polonia (Varsovia)",
  "Portugal (Lisboa)",
  "Reino Unido (Londres)",
  "República Centroafricana (Bangui)",
  "República Checa (Praga)",
  "República del Congo (Brazzaville)",
  "República Democrática del Congo (Kinsasa)",
  "República Dominicana (Santo Domingo)",
  "Ruanda (Kigali)",
  "Rumania (Bucarest)",
  "Rusia (Moscú)",
  "Samoa (Apia)",
  "San Cristóbal y Nieves (Basseterre)",
  "San Marino (San Marino)",
  "San Vicente y las Granadinas (Kingstown)",
  "Santa Lucía (Castries)",
  "Santo Tomé y Príncipe (Santo Tomé)",
  "Senegal (Dakar)",
  "Serbia (Belgrado)",
  "Seychelles (Victoria)",
  "Sierra Leona (Freetown)",
  "Singapur (Singapur)",
  "Siria (Damasco)",
  "Somalia (Mogadiscio)",
  "Sri Lanka (Sri Jayawardenapura Kotte)",
  "Suazilandia (Mbabane)",
  "Sudáfrica (Pretoria)",
  "Sudán (Jartum)",
  "Sudán del Sur (Yuba)",
  "Suecia (Estocolmo)",
  "Suiza (Berna)",
  "Surinam (Paramaribo)",
  "Tailandia (Bangkok)",
  "Tanzania (Dodoma)",
  "Tayikistán (Dusambé)",
  "Timor Oriental (Dili)",
  "Togo (Lomé)",
  "Tonga (Nukualofa)",
  "Trinidad y Tobago (Puerto España)",
  "Túnez (Túnez)",
  "Turkmenistán (Asjabad)",
  "Turquía (Ankara)",
  "Tuvalu (Funafuti)",
  "Ucrania (Kiev)",
  "Uganda (Kampala)",
  "Uruguay (Montevideo)",
  "Uzbekistán (Taskent)",
  "Vanuatu (Port Vila)",
  "Venezuela (Caracas)",
  "Vietnam (Hanói)",
  "Yemen (Saná)",
  "Yibuti (Yibuti)",
  "Zambia (Lusaka)",
  "Zimbabue (Harare)",

  // ===== CIUDADES IMPORTANTES DE AMÉRICA =====
  // Norteamérica
  "Nueva York",
  "Los Ángeles",
  "Chicago",
  "Houston",
  "Miami",
  "San Francisco",
  "Toronto",
  "Montreal",
  "Vancouver",
  "Ciudad de México",
  "Guadalajara",
  "Monterrey",
  "Cancún",
  "La Habana",
  "Kingston",
  "Nasáu",
  "Puerto Príncipe",
  "Santo Domingo",
  "San Juan",

  // Centroamérica
  "Ciudad de Panamá",
  "San José",
  "Managua",
  "Tegucigalpa",
  "San Salvador",
  "Ciudad de Guatemala",
  "Belmopán",

  // Sudamérica
  "Buenos Aires",
  "Córdoba",
  "Rosario",
  "Mendoza",
  "La Paz",
  "Santa Cruz de la Sierra",
  "El Alto",
  "Brasilia",
  "São Paulo",
  "Río de Janeiro",
  "Salvador",
  "Fortaleza",
  "Belo Horizonte",
  "Manaus",
  "Curitiba",
  "Recife",
  "Porto Alegre",
  "Santiago",
  "Valparaíso",
  "Concepción",
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Cúcuta",
  "Bucaramanga",
  "Pereira",
  "Santa Marta",
  "Ibagué",
  "Villavicencio",
  "Manizales",
  "Pasto",
  "Neiva",
  "Armenia",
  "Quito",
  "Guayaquil",
  "Cuenca",
  "Asunción",
  "Ciudad del Este",
  "Lima",
  "Arequipa",
  "Cusco",
  "Trujillo",
  "Paramaribo",
  "Montevideo",
  "Caracas",
  "Maracaibo",
  "Valencia",
  "Barquisimeto",
  "Maracay",
  "Ciudad Guayana",
  "Georgetown",
  "Cayena",

  // ===== DEPARTAMENTOS Y MUNICIPIOS DE COLOMBIA =====
  // Amazonas
  "Amazonas",
  "Leticia",
  "Puerto Nariño",
  "La Chorrera",
  "La Pedrera",
  "La Victoria",
  "Mirití-Paraná",
  "Puerto Alegría",
  "Puerto Arica",
  "Puerto Santander",
  "Tarapacá",

  // Antioquia
  "Antioquia",
  "Medellín",
  "Abejorral",
  "Abriaquí",
  "Alejandría",
  "Amagá",
  "Amalfi",
  "Andes",
  "Angelópolis",
  "Angostura",
  "Anorí",
  "Anzá",
  "Apartadó",
  "Arboletes",
  "Argelia",
  "Armenia",
  "Barbosa",
  "Bello",
  "Belmira",
  "Betania",
  "Betulia",
  "Briceño",
  "Buriticá",
  "Cáceres",
  "Caicedo",
  "Caldas",
  "Campamento",
  "Cañasgordas",
  "Caracolí",
  "Caramanta",
  "Carepa",
  "Carmen de Viboral",
  "Carolina del Príncipe",
  "Caucasia",
  "Chigorodó",
  "Cisneros",
  "Ciudad Bolívar",
  "Cocorná",
  "Concepción",
  "Concordia",
  "Copacabana",
  "Dabeiba",
  "Donmatías",
  "Ebéjico",
  "El Bagre",
  "El Carmen de Viboral",
  "El Peñol",
  "El Retiro",
  "El Santuario",
  "Entrerríos",
  "Envigado",
  "Fredonia",
  "Frontino",
  "Giraldo",
  "Girardota",
  "Gómez Plata",
  "Granada",
  "Guadalupe",
  "Guarne",
  "Guatapé",
  "Heliconia",
  "Hispania",
  "Itagüí",
  "Ituango",
  "Jardín",
  "Jericó",
  "La Ceja",
  "La Estrella",
  "La Pintada",
  "La Unión",
  "Liborina",
  "Maceo",
  "Marinilla",
  "Montebello",
  "Murindó",
  "Mutatá",
  "Nariño",
  "Nechí",
  "Necoclí",
  "Olaya",
  "Peque",
  "Pueblorrico",
  "Puerto Berrío",
  "Puerto Nare",
  "Puerto Triunfo",
  "Remedios",
  "Rionegro",
  "Sabanalarga",
  "Sabaneta",
  "Salgar",
  "San Andrés de Cuerquia",
  "San Carlos",
  "San Francisco",
  "San Jerónimo",
  "San José de la Montaña",
  "San Juan de Urabá",
  "San Luis",
  "San Pedro de los Milagros",
  "San Pedro de Urabá",
  "San Rafael",
  "San Roque",
  "San Vicente Ferrer",
  "Santa Bárbara",
  "Santa Fe de Antioquia",
  "Santa Rosa de Osos",
  "Santo Domingo",
  "Santuario",
  "Segovia",
  "Sonsón",
  "Sopetrán",
  "Támesis",
  "Tarazá",
  "Tarso",
  "Titiribí",
  "Toledo",
  "Turbo",
  "Uramita",
  "Urrao",
  "Valdivia",
  "Valparaíso",
  "Vegachí",
  "Venecia",
  "Vigía del Fuerte",
  "Yalí",
  "Yarumal",
  "Yolombó",
  "Yondó",
  "Zaragoza",

  // Arauca
  "Arauca",
  "Saravena",
  "Tame",
  "Arauquita",
  "Cravo Norte",
  "Fortul",
  "Puerto Rondón",

  // Atlántico
  "Atlántico",
  "Barranquilla",
  "Baranoa",
  "Campo de la Cruz",
  "Candelaria",
  "Galapa",
  "Juan de Acosta",
  "Luruaco",
  "Malambo",
  "Manatí",
  "Palmar de Varela",
  "Piojó",
  "Polonuevo",
  "Ponedera",
  "Puerto Colombia",
  "Repelón",
  "Sabanagrande",
  "Sabanalarga",
  "Santa Lucía",
  "Santo Tomás",
  "Soledad",
  "Suan",
  "Tubará",
  "Usiacurí",

  // Bolívar
  "Bolívar",
  "Cartagena de Indias",
  "Achí",
  "Altos del Rosario",
  "Arenal",
  "Arjona",
  "Arroyohondo",
  "Barranco de Loba",
  "Calamar",
  "Cantagallo",
  "Cicuco",
  "Córdoba",
  "Clemencia",
  "El Carmen de Bolívar",
  "El Guamo",
  "El Peñón",
  "Hatillo de Loba",
  "Magangué",
  "Mahates",
  "Margarita",
  "Mompós",
  "Montecristo",
  "Morales",
  "Norosí",
  "Pinillos",
  "Regidor",
  "Río Viejo",
  "San Cristóbal",
  "San Estanislao",
  "San Fernando",
  "San Jacinto",
  "San Jacinto del Cauca",
  "San Juan Nepomuceno",
  "San Martín de Loba",
  "San Pablo",
  "Santa Catalina",
  "Santa Rosa",
  "Santa Rosa del Sur",
  "Simití",
  "Soplaviento",
  "Talaigua Nuevo",
  "Tiquisio",
  "Turbaco",
  "Turbaná",
  "Villanueva",
  "Zambrano",

  // Boyacá
  "Boyacá",
  "Tunja",
  "Almeida",
  "Aquitania",
  "Arcabuco",
  "Belén",
  "Berbeo",
  "Betéitiva",
  "Boavita",
  "Boyacá",
  "Briceño",
  "Buenavista",
  "Caldas",
  "Campohermoso",
  "Cerinza",
  "Chinavita",
  "Chiquinquirá",
  "Chíquiza",
  "Chiscas",
  "Chita",
  "Chitaraque",
  "Chivatá",
  "Chivor",
  "Ciénega",
  "Cómbita",
  "Coper",
  "Corrales",
  "Covarachía",
  "Cubará",
  "Cucaita",
  "Cuítiva",
  "Duitama",
  "El Cocuy",
  "El Espino",
  "Firavitoba",
  "Floresta",
  "Gachantivá",
  "Gámeza",
  "Garagoa",
  "Guacamayas",
  "Guateque",
  "Guayatá",
  "Güicán",
  "Iza",
  "Jenesano",
  "Jericó",
  "La Capilla",
  "La Uvita",
  "La Victoria",
  "Labranzagrande",
  "Macanal",
  "Maripí",
  "Miraflores",
  "Mongua",
  "Monguí",
  "Moniquirá",
  "Motavita",
  "Muzo",
  "Nobsa",
  "Nuevo Colón",
  "Oicatá",
  "Otanche",
  "Pachavita",
  "Páez",
  "Paipa",
  "Pajarito",
  "Panqueba",
  "Pauna",
  "Paya",
  "Paz de Río",
  "Pesca",
  "Pisba",
  "Puerto Boyacá",
  "Quípama",
  "Ramiriquí",
  "Ráquira",
  "Rondón",
  "Saboyá",
  "Sáchica",
  "Samacá",
  "San Eduardo",
  "San José de Pare",
  "San Luis de Gaceno",
  "San Mateo",
  "San Miguel de Sema",
  "San Pablo de Borbur",
  "Santa María",
  "Santa Rosa de Viterbo",
  "Santa Sofía",
  "Santana",
  "Sativanorte",
  "Sativasur",
  "Siachoque",
  "Soatá",
  "Socha",
  "Socotá",
  "Sogamoso",
  "Somondoco",
  "Sora",
  "Soracá",
  "Sotaquirá",
  "Susacón",
  "Sutamarchán",
  "Sutatenza",
  "Tasco",
  "Tenza",
  "Tibaná",
  "Tibasosa",
  "Tinjacá",
  "Tipacoque",
  "Toca",
  "Togüí",
  "Tópaga",
  "Tota",
  "Tununguá",
  "Turmequé",
  "Tuta",
  "Tutazá",
  "Úmbita",
  "Ventaquemada",
  "Villa de Leyva",
  "Viracachá",
  "Zetaquira",

  // Caldas
  "Caldas",
  "Manizales",
  "Aguadas",
  "Anserma",
  "Aranzazu",
  "Belalcázar",
  "Chinchiná",
  "Filadelfia",
  "La Dorada",
  "La Merced",
  "Manzanares",
  "Marmato",
  "Marquetalia",
  "Marulanda",
  "Neira",
  "Norcasia",
  "Pácora",
  "Palestina",
  "Pensilvania",
  "Riosucio",
  "Risaralda",
  "Salamina",
  "Samaná",
  "San José",
  "Supía",
  "Victoria",
  "Villamaría",
  "Viterbo",

  // Caquetá
  "Caquetá",
  "Florencia",
  "Albania",
  "Belén de los Andaquíes",
  "Cartagena del Chairá",
  "Curillo",
  "El Doncello",
  "El Paujil",
  "La Montañita",
  "Milán",
  "Morelia",
  "Puerto Rico",
  "San José del Fragua",
  "San Vicente del Caguán",
  "Solano",
  "Solita",
  "Valparaíso",

  // Casanare
  "Casanare",
  "Yopal",
  "Aguazul",
  "Chámeza",
  "Hato Corozal",
  "La Salina",
  "Maní",
  "Monterrey",
  "Nunchía",
  "Orocué",
  "Paz de Ariporo",
  "Pore",
  "Recetor",
  "Sabanalarga",
  "Sácama",
  "San Luis de Gaceno",
  "Támara",
  "Tauramena",
  "Trinidad",
  "Villanueva",

  // Cauca
  "Cauca",
  "Popayán",
  "Almaguer",
  "Argelia",
  "Balboa",
  "Bolívar",
  "Buenos Aires",
  "Cajibío",
  "Caldono",
  "Caloto",
  "Corinto",
  "El Tambo",
  "Florencia",
  "Guachené",
  "Guapi",
  "Inzá",
  "Jambaló",
  "La Sierra",
  "La Vega",
  "López de Micay",
  "Mercaderes",
  "Miranda",
  "Morales",
  "Padilla",
  "Páez",
  "Patía",
  "Piamonte",
  "Piendamó",
  "Puerto Tejada",
  "Puracé",
  "Rosas",
  "San Sebastián",
  "Santa Rosa",
  "Santander de Quilichao",
  "Silvia",
  "Sotará",
  "Suárez",
  "Sucre",
  "Timbío",
  "Timbiquí",
  "Toribío",
  "Totoró",
  "Villa Rica",

  // Cesar
  "Cesar",
  "Valledupar",
  "Aguachica",
  "Agustín Codazzi",
  "Astrea",
  "Becerril",
  "Bosconia",
  "Chimichagua",
  "Chiriguaná",
  "Curumaní",
  "El Copey",
  "El Paso",
  "Gamarra",
  "González",
  "La Gloria",
  "La Jagua de Ibirico",
  "La Paz",
  "Manaure",
  "Pailitas",
  "Pelaya",
  "Pueblo Bello",
  "Río de Oro",
  "San Alberto",
  "San Diego",
  "San Martín",
  "Tamalameque",

  // Chocó
  "Chocó",
  "Quibdó",
  "Acandí",
  "Alto Baudó",
  "Bagadó",
  "Bahía Solano",
  "Bajo Baudó",
  "Bojayá",
  "Cantón de San Pablo",
  "Cértegui",
  "Condoto",
  "El Cantón del San Pablo",
  "El Carmen de Atrato",
  "El Litoral del San Juan",
  "Istmina",
  "Juradó",
  "Lloró",
  "Medio Atrato",
  "Medio Baudó",
  "Medio San Juan",
  "Nóvita",
  "Nuquí",
  "Río Iró",
  "Río Quito",
  "Riosucio",
  "San José del Palmar",
  "Sipí",
  "Tadó",
  "Unguía",
  "Unión Panamericana",

  // Córdoba
  "Córdoba",
  "Montería",
  "Ayapel",
  "Buenavista",
  "Canalete",
  "Cereté",
  "Chimá",
  "Chinú",
  "Ciénaga de Oro",
  "Cotorra",
  "La Apartada",
  "Lorica",
  "Los Córdobas",
  "Momil",
  "Moñitos",
  "Montelíbano",
  "Planeta Rica",
  "Pueblo Nuevo",
  "Puerto Escondido",
  "Puerto Libertador",
  "Purísima",
  "Sahagún",
  "San Andrés de Sotavento",
  "San Antero",
  "San Bernardo del Viento",
  "San Carlos",
  "San José de Uré",
  "San Pelayo",
  "Tierralta",
  "Tuchín",
  "Valencia",

  // Cundinamarca
  "Cundinamarca",
  "Bogotá D.C.",
  "Agua de Dios",
  "Albán",
  "Anapoima",
  "Anolaima",
  "Apulo",
  "Arbeláez",
  "Beltrán",
  "Bituima",
  "Bojacá",
  "Cabrera",
  "Cachipay",
  "Cajicá",
  "Caparrapí",
  "Cáqueza",
  "Carmen de Carupa",
  "Chaguaní",
  "Chía",
  "Chipaque",
  "Choachí",
  "Chocontá",
  "Cogua",
  "Cota",
  "Cucunubá",
  "El Colegio",
  "El Peñón",
  "El Rosal",
  "Facatativá",
  "Fómeque",
  "Fosca",
  "Funza",
  "Fúquene",
  "Fusagasugá",
  "Gachalá",
  "Gachancipá",
  "Gachetá",
  "Gama",
  "Girardot",
  "Granada",
  "Guachetá",
  "Guaduas",
  "Guasca",
  "Guataquí",
  "Guatavita",
  "Guayabal de Síquima",
  "Guayabetal",
  "Gutiérrez",
  "Jerusalén",
  "Junín",
  "La Calera",
  "La Mesa",
  "La Palma",
  "La Peña",
  "La Vega",
  "Lenguazaque",
  "Machetá",
  "Madrid",
  "Manta",
  "Medina",
  "Mosquera",
  "Nariño",
  "Nemocón",
  "Nilo",
  "Nimaima",
  "Nocaima",
  "Pacho",
  "Paime",
  "Pandi",
  "Paratebueno",
  "Pasca",
  "Puerto Salgar",
  "Pulí",
  "Quebradanegra",
  "Quetame",
  "Quipile",
  "Ricaurte",
  "San Antonio del Tequendama",
  "San Bernardo",
  "San Cayetano",
  "San Francisco",
  "San Juan de Rioseco",
  "Sasaima",
  "Sesquilé",
  "Sibaté",
  "Silvania",
  "Simijaca",
  "Soacha",
  "Sopó",
  "Subachoque",
  "Suesca",
  "Supatá",
  "Susa",
  "Sutatausa",
  "Tabio",
  "Tausa",
  "Tena",
  "Tenjo",
  "Tibacuy",
  "Tibirita",
  "Tocaima",
  "Tocancipá",
  "Topaipí",
  "Ubalá",
  "Ubaque",
  "Ubaté",
  "Une",
  "Útica",
  "Venecia",
  "Vergara",
  "Vianí",
  "Villagómez",
  "Villapinzón",
  "Villeta",
  "Viotá",
  "Yacopí",
  "Zipacón",
  "Zipaquirá",

  // Guainía
  "Guainía",
  "Inírida",
  "Barranco Minas",
  "Cacahual",
  "La Guadalupe",
  "Mapiripana",
  "Morichal",
  "Pana Pana",
  "Puerto Colombia",
  "San Felipe",

  // Guaviare
  "Guaviare",
  "San José del Guaviare",
  "Calamar",
  "El Retorno",
  "Miraflores",

  // Huila
  "Huila",
  "Neiva",
  "Acevedo",
  "Agrado",
  "Aipe",
  "Algeciras",
  "Altamira",
  "Baraya",
  "Campoalegre",
  "Colombia",
  "Elías",
  "Garzón",
  "Gigante",
  "Guadalupe",
  "Hobo",
  "Íquira",
  "Isnos",
  "La Argentina",
  "La Plata",
  "Nátaga",
  "Oporapa",
  "Paicol",
  "Palermo",
  "Palestina",
  "Pital",
  "Pitalito",
  "Rivera",
  "Saladoblanco",
  "San Agustín",
  "Santa María",
  "Suaza",
  "Tarqui",
  "Tello",
  "Teruel",
  "Tesalia",
  "Timaná",
  "Villavieja",
  "Yaguará",

  // La Guajira
  "La Guajira",
  "Riohacha",
  "Albania",
  "Barrancas",
  "Dibulla",
  "Distracción",
  "El Molino",
  "Fonseca",
  "Hatonuevo",
  "La Jagua del Pilar",
  "Maicao",
  "Manaure",
  "San Juan del Cesar",
  "Uribia",
  "Urumita",
  "Villanueva",

  // Magdalena
  "Magdalena",
  "Santa Marta",
  "Algarrobo",
  "Aracataca",
  "Ariguaní",
  "Cerro de San Antonio",
  "Chibolo",
  "Chivolo",
  "Ciénaga",
  "Concordia",
  "El Banco",
  "El Piñón",
  "El Retén",
  "Fundación",
  "Guamal",
  "Nueva Granada",
  "Pedraza",
  "Pijiño del Carmen",
  "Pivijay",
  "Plato",
  "Puebloviejo",
  "Remolino",
  "Sabanas de San Ángel",
  "Salamina",
  "San Sebastián de Buenavista",
  "San Zenón",
  "Santa Ana",
  "Santa Bárbara de Pinto",
  "Sitionuevo",
  "Tenerife",
  "Zapayán",
  "Zona Bananera",

  // Meta
  "Meta",
  "Villavicencio",
  "Acacías",
  "Barranca de Upía",
  "Cabuyaro",
  "Castilla la Nueva",
  "Cubarral",
  "Cumaral",
  "El Calvario",
  "El Castillo",
  "El Dorado",
  "Fuente de Oro",
  "Granada",
  "Guamal",
  "La Macarena",
  "Lejanías",
  "Mapiripán",
  "Mesetas",
  "Puerto Concordia",
  "Puerto Gaitán",
  "Puerto Lleras",
  "Puerto López",
  "Puerto Rico",
  "Restrepo",
  "San Carlos de Guaroa",
  "San Juan de Arama",
  "San Juanito",
  "San Martín",
  "Uribe",
  "Vista Hermosa",

  // Nariño
  "Nariño",
  "Pasto",
  "Albán",
  "Aldana",
  "Ancuya",
  "Arboleda",
  "Barbacoas",
  "Belén",
  "Buesaco",
  "Chachagüí",
  "Colón",
  "Consacá",
  "Contadero",
  "Córdoba",
  "Cuaspud",
  "Cumbal",
  "Cumbitara",
  "El Charco",
  "El Peñol",
  "El Rosario",
  "El Tablón de Gómez",
  "El Tambo",
  "Francisco Pizarro",
  "Funes",
  "Guachucal",
  "Guaitarilla",
  "Gualmatán",
  "Iles",
  "Imués",
  "Ipiales",
  "La Cruz",
  "La Florida",
  "La Llanada",
  "La Tola",
  "La Unión",
  "Leiva",
  "Linares",
  "Los Andes",
  "Magüí Payán",
  "Mallama",
  "Mosquera",
  "Nariño",
  "Olaya Herrera",
  "Ospina",
  "Policarpa",
  "Potosí",
  "Providencia",
  "Puerres",
  "Pupiales",
  "Ricaurte",
  "Roberto Payán",
  "Samaniego",
  "San Andrés de Tumaco",
  "San Bernardo",
  "San Lorenzo",
  "San Pablo",
  "San Pedro de Cartago",
  "Sandona",
  "Santa Bárbara",
  "Sapuyes",
  "Sibundoy",
  "Taminango",
  "Tangua",
  "Tumaco",
  "Túquerres",
  "Yacuanquer",

  // Norte de Santander
  "Norte de Santander",
  "San José de Cúcuta",
  "Ábrego",
  "Arboledas",
  "Bochalema",
  "Bucarasica",
  "Chinácota",
  "Chitagá",
  "Convención",
  "Cúcuta",
  "Cáchira",
  "Cácota",
  "Durania",
  "El Carmen",
  "El Tarra",
  "El Zulia",
  "Gramalote",
  "Hacarí",
  "Herrán",
  "La Esperanza",
  "La Playa de Belén",
  "Labateca",
  "Los Patios",
  "Lourdes",
  "Mutiscua",
  "Ocaña",
  "Pamplona",
  "Pamplonita",
  "Puerto Santander",
  "Ragonvalia",
  "Salazar",
  "San Calixto",
  "San Cayetano",
  "Santiago",
  "Santo Domingo de Silos",
  "Sardinata",
  "Teorama",
  "Tibú",
  "Toledo",
  "Villa Caro",
  "Villa del Rosario",

  // Putumayo
  "Putumayo",
  "Mocoa",
  "Colón",
  "Leguízamo",
  "Orito",
  "Puerto Asís",
  "Puerto Caicedo",
  "Puerto Guzmán",
  "Puerto Leguízamo",
  "San Francisco",
  "San Miguel",
  "Santiago",
  "Sibundoy",
  "Valle del Guamuez",
  "Villagarzón",

  // Quindío
  "Quindío",
  "Armenia",
  "Buenavista",
  "Calarcá",
  "Circasia",
  "Córdoba",
  "Filandia",
  "Génova",
  "La Tebaida",
  "Montenegro",
  "Pijao",
  "Quimbaya",
  "Salento",

  // Risaralda
  "Risaralda",
  "Pereira",
  "Apía",
  "Balboa",
  "Belén de Umbría",
  "Dosquebradas",
  "Guática",
  "La Celia",
  "La Virginia",
  "Marsella",
  "Mistrató",
  "Pueblo Rico",
  "Quinchía",
  "Santa Rosa de Cabal",
  "Santuario",

  // San Andrés y Providencia
  "San Andrés y Providencia",
  "San Andrés",
  "Providencia",

  // Santander
  "Santander",
  "Bucaramanga",
  "Aguada",
  "Albania",
  "Aratoca",
  "Barbosa",
  "Barichara",
  "Barrancabermeja",
  "Betulia",
  "Bolívar",
  "Cabrera",
  "California",
  "Capitanejo",
  "Carcasí",
  "Cepitá",
  "Cerrito",
  "Charalá",
  "Charta",
  "Chima",
  "Chipatá",
  "Cimitarra",
  "Concepción",
  "Confines",
  "Contratación",
  "Coromoro",
  "Curití",
  "El Carmen de Chucurí",
  "El Guacamayo",
  "El Peñón",
  "El Playón",
  "Encino",
  "Enciso",
  "Florián",
  "Floridablanca",
  "Galán",
  "Gámbita",
  "Girón",
  "Guaca",
  "Guadalupe",
  "Guapotá",
  "Guavatá",
  "Guepsa",
  "Hato",
  "Jesús María",
  "Jordán",
  "La Belleza",
  "La Paz",
  "Landázuri",
  "Lebrija",
  "Los Santos",
  "Macaravita",
  "Málaga",
  "Matanza",
  "Mogotes",
  "Molagavita",
  "Ocamonte",
  "Oiba",
  "Onzaga",
  "Palmar",
  "Palmas del Socorro",
  "Páramo",
  "Piedecuesta",
  "Pinchote",
  "Puente Nacional",
  "Puerto Parra",
  "Puerto Wilches",
  "Rionegro",
  "Sabana de Torres",
  "San Andrés",
  "San Benito",
  "San Gil",
  "San Joaquín",
  "San José de Miranda",
  "San Miguel",
  "San Vicente de Chucurí",
  "Santa Bárbara",
  "Santa Helena del Opón",
  "Simacota",
  "Socorro",
  "Suaita",
  "Sucre",
  "Suratá",
  "Tona",
  "Valle de San José",
  "Vélez",
  "Vetas",
  "Villanueva",
  "Zapatoca",

  // Sucre
  "Sucre",
  "Sincelejo",
  "Buenavista",
  "Caimito",
  "Chalán",
  "Colosó",
  "Corozal",
  "Coveñas",
  "El Roble",
  "Galeras",
  "Guaranda",
  "La Unión",
  "Los Palmitos",
  "Majagual",
  "Morroa",
  "Ovejas",
  "Palmito",
  "Sampués",
  "San Benito Abad",
  "San Juan de Betulia",
  "San Marcos",
  "San Onofre",
  "San Pedro",
  "Santiago de Tolú",
  "Sincelejo",
  "Sucre",
  "Tolú",
  "Toluviejo",

  // Tolima
  "Tolima",
  "Ibagué",
  "Alpujarra",
  "Alvarado",
  "Ambalema",
  "Anzoátegui",
  "Armero",
  "Ataco",
  "Cajamarca",
  "Carmen de Apicalá",
  "Casabianca",
  "Chaparral",
  "Coello",
  "Coyaima",
  "Cunday",
  "Dolores",
  "El Espinal",
  "Falán",
  "Flandes",
  "Fresno",
  "Guamo",
  "Herveo",
  "Honda",
  "Icononzo",
  "Lérida",
  "Líbano",
  "Mariquita",
  "Melgar",
  "Murillo",
  "Natagaima",
  "Ortega",
  "Palocabildo",
  "Piedras",
  "Planadas",
  "Prado",
  "Purificación",
  "Rioblanco",
  "Roncesvalles",
  "Rovira",
  "Saldaña",
  "San Antonio",
  "San Luis",
  "Santa Isabel",
  "Suárez",
  "Valle de San Juan",
  "Venadillo",
  "Villahermosa",
  "Villarrica",

  // Valle del Cauca
  "Valle del Cauca",
  "Cali",
  "Alcalá",
  "Andalucía",
  "Ansermanuevo",
  "Argelia",
  "Bolívar",
  "Buenaventura",
  "Buga",
  "Bugalagrande",
  "Caicedonia",
  "Calima",
  "Candelaria",
  "Cartago",
  "Dagua",
  "El Águila",
  "El Cairo",
  "El Cerrito",
  "El Dovio",
  "Florida",
  "Ginebra",
  "Guacarí",
  "Jamundí",
  "La Cumbre",
  "La Unión",
  "La Victoria",
  "Obando",
  "Palmira",
  "Pradera",
  "Restrepo",
  "Riofrío",
  "Roldanillo",
  "San Pedro",
  "Sevilla",
  "Toro",
  "Trujillo",
  "Tuluá",
  "Ulloa",
  "Versalles",
  "Vijes",
  "Yotoco",
  "Yumbo",
  "Zarzal",

  // Vaupés
  "Vaupés",
  "Mitú",
  "Carurú",
  "Pacoa",
  "Papunahua",
  "Taraira",
  "Yavaraté",

  // Vichada
  "Vichada",
  "Puerto Carreño",
  "Cumaribo",
  "La Primavera",
  "Santa Rosalía",
];

const CENTROS = [
  "C (Do)",
  "C# / Db (Do# / Reb)",
  "D (Re)",
  "D# / Eb (Re# / Mib)",
  "E (Mi)",
  "F (Fa)",
  "F# / Gb (Fa# / Solb)",
  "G (Sol)",
  "G# / Ab (Sol# / Lab)",
  "A (La)",
  "A# / Bb (La# / Sib)",
  "B (Si)",
];
require("../app/models/lista.server.model");
const Lista = require("mongoose").model("Lista");

const seed = async () => {
  try {
    // --- lugares ---
    console.log("🗑️  Eliminando lista 'lugares' existente...");
    await Lista.deleteOne({ nombre_lista: "lugares" });
    console.log("✅ Lista 'lugares' eliminada");

    const lugaresFiltrados = Array.from(
      new Set(LUGARES.map((el) => (el ? el.trim() : "")))
    ).filter((el) => el !== "");

    const listaLugares = new Lista({
      nombre_lista: "lugares",
      elementos: lugaresFiltrados,
      metadata: null,
    });

    await listaLugares.save();
    console.log(`✅ Lista 'lugares' creada con ${lugaresFiltrados.length} elementos`);

    // --- centros (tonalidades) ---
    console.log("🗑️  Eliminando lista 'centros' existente...");
    await Lista.deleteOne({ nombre_lista: "centros" });
    console.log("✅ Lista 'centros' eliminada");

    const centrosFiltrados = CENTROS.filter((el) => el && el.trim() !== "");

    const listaCentros = new Lista({
      nombre_lista: "centros",
      elementos: centrosFiltrados,
      metadata: null,
    });

    await listaCentros.save();
    console.log(`✅ Lista 'centros' creada con ${centrosFiltrados.length} elementos`);
  } catch (error) {
    console.error("❌ Error:", error);
    process.exit(1);
  }
};

const main = async () => {
  await connectDB();
  await seed();
  await mongoose.disconnect();
  console.log("🔌 Desconectado de MongoDB");
  process.exit(0);
};

main();
