// Configuración de AccessControl para roles y permisos
const AccessControl = require("accesscontrol");

const ac = new AccessControl();

// Definir permisos por rol
ac.grant("user")
  // Usuarios pueden ver y editar su propio perfil
  .readOwn("user")
  .updateOwn("user")
  // Usuarios pueden ver obras, recursos, etc. (solo lectura)
  .readAny("obra")
  .readAny("recurso")
  .readAny("proyecto")
  .readAny("medio")
  .readAny("sistema")
  .readAny("coleccion")
  .readAny("ejemplar")
  .readAny("genero")
  .readAny("materia")
  .readAny("instrumento")
  .readAny("fondo")
  .readAny("archivo")
  .readAny("diccionario")
  .readAny("idioma")
  // Usuarios pueden usar el sistema de búsqueda
  .readAny("search");

ac.grant("editor")
  .extend("user")
  // Editores pueden crear y editar sus propios recursos
  .createOwn("obra")
  .updateOwn("obra")
  .createOwn("recurso")
  .updateOwn("recurso")
  .createOwn("proyecto")
  .updateOwn("proyecto")
  .createOwn("medio")
  .updateOwn("medio")
  .createOwn("sistema")
  .updateOwn("sistema")
  .createOwn("coleccion")
  .updateOwn("coleccion")
  .createOwn("ejemplar")
  .updateOwn("ejemplar")
  .createOwn("genero")
  .updateOwn("genero")
  .createOwn("materia")
  .updateOwn("materia")
  .createOwn("instrumento")
  .updateOwn("instrumento")
  .createOwn("fondo")
  .updateOwn("fondo")
  .createOwn("archivo")
  .updateOwn("archivo")
  .createOwn("diccionario")
  .updateOwn("diccionario")
  .createOwn("idioma")
  .updateOwn("idioma")
  // Editores pueden eliminar sus propios recursos
  .deleteOwn("obra")
  .deleteOwn("recurso")
  .deleteOwn("proyecto")
  .deleteOwn("medio")
  .deleteOwn("sistema")
  .deleteOwn("coleccion")
  .deleteOwn("ejemplar")
  .deleteOwn("genero")
  .deleteOwn("materia")
  .deleteOwn("instrumento")
  .deleteOwn("fondo")
  .deleteOwn("archivo")
  .deleteOwn("diccionario")
  .deleteOwn("idioma");

ac.grant("admin")
  .extend("editor")
  // Administradores pueden gestionar todos los recursos
  .createAny("obra")
  .readAny("obra")
  .updateAny("obra")
  .deleteAny("obra")
  .createAny("recurso")
  .readAny("recurso")
  .updateAny("recurso")
  .deleteAny("recurso")
  .createAny("proyecto")
  .readAny("proyecto")
  .updateAny("proyecto")
  .deleteAny("proyecto")
  .createAny("medio")
  .readAny("medio")
  .updateAny("medio")
  .deleteAny("medio")
  .createAny("sistema")
  .readAny("sistema")
  .updateAny("sistema")
  .deleteAny("sistema")
  .createAny("coleccion")
  .readAny("coleccion")
  .updateAny("coleccion")
  .deleteAny("coleccion")
  .createAny("ejemplar")
  .readAny("ejemplar")
  .updateAny("ejemplar")
  .deleteAny("ejemplar")
  .createAny("genero")
  .readAny("genero")
  .updateAny("genero")
  .deleteAny("genero")
  .createAny("materia")
  .readAny("materia")
  .updateAny("materia")
  .deleteAny("materia")
  .createAny("instrumento")
  .readAny("instrumento")
  .updateAny("instrumento")
  .deleteAny("instrumento")
  .createAny("fondo")
  .readAny("fondo")
  .updateAny("fondo")
  .deleteAny("fondo")
  .createAny("archivo")
  .readAny("archivo")
  .updateAny("archivo")
  .deleteAny("archivo")
  .createAny("diccionario")
  .readAny("diccionario")
  .updateAny("diccionario")
  .deleteAny("diccionario")
  .createAny("idioma")
  .readAny("idioma")
  .updateAny("idioma")
  .deleteAny("idioma")
  // Administradores pueden gestionar usuarios
  .createAny("user")
  .readAny("user")
  .updateAny("user")
  .deleteAny("user");

// Bloquear configuración para evitar modificaciones accidentales
ac.lock();

module.exports = ac;
